import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { ActionSheetIOS, Alert, Platform } from "react-native";

/**
 * Fetch a print HTML endpoint from the API server (HTML is generated by
 * `@workspace/print-html` so output is identical to the web 版).
 *
 * UX = Web 版と同じ感覚で:
 *  - 「印刷」 → OS の印刷プレビューを開く (iOS/Android の標準印刷シート)
 *      iOS の場合、印刷シート内で「PDFとして保存」 / AirPrint /
 *      AirDrop が選択可能。
 *  - 「PDFを保存・共有」 → PDFファイルを生成して共有シートを開く
 *      (iOS の "ファイルに保存" / メール / Drive 等)。
 *
 * 利用者は「PDF・印刷」 ボタンをタップ → アクションシートで選択。
 */
export async function printApiDoc(opts: {
  path: string; // "/api/print/invoice/:id"
  fileName: string; // "請求書-INV001.pdf"
  getToken: () => Promise<string | null>;
}): Promise<void> {
  // Web (Safari/Chrome on iPad など) では expo-print も Alert のマルチボタンも
  // 信頼できないので、HTML を新しいタブで開いてブラウザネイティブの
  // 印刷 / PDF保存 を使ってもらう。
  if (Platform.OS === "web") {
    const html = await fetchPrintHtml(opts.path, opts.getToken);
    openHtmlInNewTabAndPrint(html, opts.fileName);
    return;
  }

  const action = await pickPrintAction();
  if (!action) return; // user cancelled

  const html = await fetchPrintHtml(opts.path, opts.getToken);

  if (action === "print") {
    await Print.printAsync({ html });
    return;
  }

  // share PDF file
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  let shareUri = uri;
  try {
    const dir = FileSystem.cacheDirectory ?? "";
    const target = `${dir}${opts.fileName}`;
    await FileSystem.copyAsync({ from: uri, to: target });
    shareUri = target;
  } catch {
    // fall back to original URI on copy failure
  }

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(shareUri, {
      mimeType: "application/pdf",
      dialogTitle: opts.fileName,
      UTI: "com.adobe.pdf",
    });
  } else {
    throw new Error("この端末では共有機能が利用できません");
  }
}

/**
 * Web 専用: HTML を Blob URL に変換 → 新しいタブで開く。
 * ロード後に自動で window.print() を呼ぶので、ユーザーは即「PDF として保存」
 * または「プリント」を選べる。Safari の popup blocker 回避のため
 * `window.open` は同期的にユーザー操作の延長で呼ぶ必要があるが、ここでは
 * fetch 後なのでブロックされる場合がある — その時は Blob URL を別タブで
 * 開くフォールバックとして a タグの click() を使う。
 */
function openHtmlInNewTabAndPrint(html: string, fileName: string): void {
  // Title を fileName にしておくとブラウザの "PDFとして保存" の
  // デフォルトファイル名になる。
  const titledHtml = html.replace(
    /<head>/i,
    `<head><title>${escapeHtml(fileName.replace(/\.pdf$/i, ""))}</title>`,
  );
  const blob = new Blob([titledHtml], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const win = typeof window !== "undefined" ? window.open(url, "_blank") : null;
  if (win) {
    // ロード完了後に印刷ダイアログを自動表示
    const trigger = () => {
      try {
        win.focus();
        win.print();
      } catch {
        /* ignore */
      }
    };
    win.addEventListener?.("load", trigger);
    // Safari など load イベントが取れない場合の fallback
    setTimeout(() => {
      if (!win.closed) trigger();
    }, 1500);
  } else {
    // popup blocked → ダウンロードリンクとして開く
    const a = document.createElement("a");
    a.href = url;
    a.target = "_blank";
    a.rel = "noopener";
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    a.remove();
  }
  // Blob URL は数分後に解放
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

async function fetchPrintHtml(
  path: string,
  getToken: () => Promise<string | null>,
): Promise<string> {
  const domain = process.env.EXPO_PUBLIC_DOMAIN;
  if (!domain) throw new Error("EXPO_PUBLIC_DOMAIN が未設定です");
  const token = await getToken();
  const url = `https://${domain}${path}`;
  const res = await fetch(url, {
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
  if (!res.ok) {
    throw new Error(`PDF 取得失敗 (HTTP ${res.status})`);
  }
  return await res.text();
}

type PrintAction = "print" | "share";

/** Show an OS-native action sheet to let the user choose what to do. */
function pickPrintAction(): Promise<PrintAction | null> {
  return new Promise((resolve) => {
    if (Platform.OS === "ios") {
      ActionSheetIOS.showActionSheetWithOptions(
        {
          title: "PDF・印刷",
          message: "操作を選択してください",
          options: ["キャンセル", "印刷する", "PDFを保存・共有"],
          cancelButtonIndex: 0,
        },
        (idx) => {
          if (idx === 1) resolve("print");
          else if (idx === 2) resolve("share");
          else resolve(null);
        },
      );
      return;
    }
    // Android / Web fallback: simple Alert with 3 buttons
    Alert.alert(
      "PDF・印刷",
      "操作を選択してください",
      [
        { text: "キャンセル", style: "cancel", onPress: () => resolve(null) },
        { text: "印刷する", onPress: () => resolve("print") },
        { text: "PDFを保存・共有", onPress: () => resolve("share") },
      ],
      { cancelable: true, onDismiss: () => resolve(null) },
    );
  });
}
