import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { ActionSheetIOS, Alert, Platform } from "react-native";

/**
 * Fetch a print HTML endpoint from the API server (HTML is generated by
 * `@workspace/print-html` so output is identical to the web 版).
 *
 * UX = Web 版と同じ感覚で:
 *  - 「印刷」 → OS の印刷プレビューを開く (iOS/Android の標準印刷シート)
 *      iOS の場合、印刷シート内で「PDFとして保存」 / AirPrint /
 *      AirDrop が選択可能。
 *  - 「PDFを保存・共有」 → PDFファイルを生成して共有シートを開く
 *      (iOS の "ファイルに保存" / メール / Drive 等)。
 *
 * 利用者は「PDF・印刷」 ボタンをタップ → アクションシートで選択。
 */
export async function printApiDoc(opts: {
  path: string; // "/api/print/invoice/:id"
  fileName: string; // "請求書-INV001.pdf"
  getToken: () => Promise<string | null>;
}): Promise<void> {
  // Web (Safari/Chrome on iPad など): html2pdf.js で実 PDF Blob を生成 →
  // Web Share API (PDF データそのもの) → 失敗時はダウンロードにフォールバック。
  // URL ではなく PDF データで送る (受取人がアプリ登録不要)。
  if (Platform.OS === "web") {
    const html = await fetchPrintHtml(opts.path, opts.getToken);
    await generateAndSharePdfWeb(html, opts.fileName);
    return;
  }

  const action = await pickPrintAction();
  if (!action) return; // user cancelled

  const html = await fetchPrintHtml(opts.path, opts.getToken);

  if (action === "print") {
    await Print.printAsync({ html });
    return;
  }

  // share PDF file
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  let shareUri = uri;
  try {
    const dir = FileSystem.cacheDirectory ?? "";
    const target = `${dir}${opts.fileName}`;
    await FileSystem.copyAsync({ from: uri, to: target });
    shareUri = target;
  } catch {
    // fall back to original URI on copy failure
  }

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(shareUri, {
      mimeType: "application/pdf",
      dialogTitle: opts.fileName,
      UTI: "com.adobe.pdf",
    });
  } else {
    throw new Error("この端末では共有機能が利用できません");
  }
}

/**
 * Web 専用: HTML を実 PDF Blob に変換 → Web Share API で PDF ファイルを共有
 * (ファイル送信に対応しているブラウザの場合)。失敗 / 非対応時は通常の
 * ダウンロードにフォールバック。
 *
 * Web Share API (level 2) で `files` が共有できる場合 (iOS Safari/Chrome on
 * Android など)、AirDrop/メール/LINE 等に PDF データそのものを渡せる。
 */
async function generateAndSharePdfWeb(
  html: string,
  fileName: string,
): Promise<void> {
  const pdfBlob = await renderHtmlToPdfBlob(html);

  const file = new File([pdfBlob], fileName, { type: "application/pdf" });
  const nav = typeof navigator !== "undefined" ? navigator : undefined;
  const shareData: ShareData = { files: [file], title: fileName };
  if (nav?.canShare?.(shareData) && nav.share) {
    try {
      await nav.share(shareData);
      return;
    } catch (e) {
      // ユーザーがキャンセルした場合は静かに終了
      const err = e as { name?: string };
      if (err?.name === "AbortError") return;
      // 他のエラーは下のダウンロードにフォールバック
    }
  }

  // フォールバック: PDF を直接ダウンロード
  const url = URL.createObjectURL(pdfBlob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

/**
 * HTML 文字列 → PDF Blob (web 専用)。
 *
 * サーバーが返す印刷 HTML は完全な `<!DOCTYPE html>` 文書 (head の style を
 * 含む) なので、iframe srcdoc で正しい document コンテキストでレンダリング
 * してから html2canvas-pro でキャプチャ → jsPDF で A4 PDF を組み立てる。
 * 単純に div.innerHTML に流し込むと head の style が無効化されて真っ白に
 * なる。
 */
async function renderHtmlToPdfBlob(html: string): Promise<Blob> {
  const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
    import("html2canvas-pro"),
    import("jspdf"),
  ]);

  // 画面外の iframe で HTML を完全な文書としてレンダリング
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.left = "-100000px";
  iframe.style.top = "0";
  iframe.style.width = "794px"; // A4 幅 (96dpi 換算で 210mm ≒ 794px)
  iframe.style.height = "1123px"; // A4 高さ ≒ 1123px (足りなければ拡張)
  iframe.style.border = "0";
  iframe.setAttribute("aria-hidden", "true");
  document.body.appendChild(iframe);

  try {
    // srcdoc で HTML 全体を流し込み、load 完了を待つ
    await new Promise<void>((resolve, reject) => {
      const onLoad = () => resolve();
      const onError = () => reject(new Error("PDF レンダリングに失敗しました"));
      iframe.addEventListener("load", onLoad, { once: true });
      iframe.addEventListener("error", onError, { once: true });
      iframe.srcdoc = html;
      // セーフティタイムアウト (load イベントが取れない環境用)
      setTimeout(resolve, 3000);
    });

    const doc = iframe.contentDocument;
    const win = iframe.contentWindow;
    if (!doc || !win) throw new Error("iframe document が取得できません");

    // フォント / 画像のロード完了を待機
    try {
      await doc.fonts?.ready;
    } catch {
      /* ignore */
    }
    await new Promise((r) => setTimeout(r, 200));

    const target = doc.body;
    // 内容に合わせて iframe 高さを拡張 (複数ページ対応)
    const fullHeight = Math.max(
      target.scrollHeight,
      doc.documentElement.scrollHeight,
      1123,
    );
    iframe.style.height = `${fullHeight}px`;
    await new Promise((r) => setTimeout(r, 100));

    const canvas = await html2canvas(target, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
      windowWidth: 794,
      windowHeight: fullHeight,
    });

    // jsPDF に貼り付け、複数ページに分割
    const pdf = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
    const pageWidthMm = 210;
    const pageHeightMm = 297;
    const imgWidthMm = pageWidthMm;
    const imgHeightMm = (canvas.height * imgWidthMm) / canvas.width;

    if (imgHeightMm <= pageHeightMm) {
      // 1 ページに収まる
      const imgData = canvas.toDataURL("image/jpeg", 0.95);
      pdf.addImage(imgData, "JPEG", 0, 0, imgWidthMm, imgHeightMm);
    } else {
      // 複数ページに分割: A4 高さに相当する canvas 高さ単位で切り出し
      const pxPerMm = canvas.width / pageWidthMm;
      const pageCanvasHeight = Math.floor(pageHeightMm * pxPerMm);
      let yOffset = 0;
      let pageNum = 0;
      while (yOffset < canvas.height) {
        const sliceHeight = Math.min(pageCanvasHeight, canvas.height - yOffset);
        const slice = document.createElement("canvas");
        slice.width = canvas.width;
        slice.height = sliceHeight;
        const ctx = slice.getContext("2d");
        if (!ctx) throw new Error("canvas context が取得できません");
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, slice.width, slice.height);
        ctx.drawImage(
          canvas,
          0,
          yOffset,
          canvas.width,
          sliceHeight,
          0,
          0,
          canvas.width,
          sliceHeight,
        );
        const sliceData = slice.toDataURL("image/jpeg", 0.95);
        const sliceHeightMm = (sliceHeight * pageWidthMm) / canvas.width;
        if (pageNum > 0) pdf.addPage();
        pdf.addImage(sliceData, "JPEG", 0, 0, imgWidthMm, sliceHeightMm);
        yOffset += sliceHeight;
        pageNum += 1;
      }
    }

    return pdf.output("blob");
  } finally {
    iframe.remove();
  }
}

async function fetchPrintHtml(
  path: string,
  getToken: () => Promise<string | null>,
): Promise<string> {
  const domain = process.env.EXPO_PUBLIC_DOMAIN;
  if (!domain) throw new Error("EXPO_PUBLIC_DOMAIN が未設定です");
  const token = await getToken();
  const url = `https://${domain}${path}`;
  const res = await fetch(url, {
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
  if (!res.ok) {
    throw new Error(`PDF 取得失敗 (HTTP ${res.status})`);
  }
  return await res.text();
}

type PrintAction = "print" | "share";

/** Show an OS-native action sheet to let the user choose what to do. */
function pickPrintAction(): Promise<PrintAction | null> {
  return new Promise((resolve) => {
    if (Platform.OS === "ios") {
      ActionSheetIOS.showActionSheetWithOptions(
        {
          title: "PDF・印刷",
          message: "操作を選択してください",
          options: ["キャンセル", "印刷する", "PDFを保存・共有"],
          cancelButtonIndex: 0,
        },
        (idx) => {
          if (idx === 1) resolve("print");
          else if (idx === 2) resolve("share");
          else resolve(null);
        },
      );
      return;
    }
    // Android / Web fallback: simple Alert with 3 buttons
    Alert.alert(
      "PDF・印刷",
      "操作を選択してください",
      [
        { text: "キャンセル", style: "cancel", onPress: () => resolve(null) },
        { text: "印刷する", onPress: () => resolve("print") },
        { text: "PDFを保存・共有", onPress: () => resolve("share") },
      ],
      { cancelable: true, onDismiss: () => resolve(null) },
    );
  });
}
