import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { ActionSheetIOS, Alert, Platform } from "react-native";

/**
 * Fetch a print HTML endpoint from the API server (HTML is generated by
 * `@workspace/print-html` so output is identical to the web 版).
 *
 * UX = Web 版と同じ感覚で:
 *  - 「印刷」 → OS の印刷プレビューを開く (iOS/Android の標準印刷シート)
 *      iOS の場合、印刷シート内で「PDFとして保存」 / AirPrint /
 *      AirDrop が選択可能。
 *  - 「PDFを保存・共有」 → PDFファイルを生成して共有シートを開く
 *      (iOS の "ファイルに保存" / メール / Drive 等)。
 *
 * 利用者は「PDF・印刷」 ボタンをタップ → アクションシートで選択。
 */
export async function printApiDoc(opts: {
  path: string; // "/api/print/invoice/:id"
  fileName: string; // "請求書-INV001.pdf"
  getToken: () => Promise<string | null>;
}): Promise<void> {
  const action = await pickPrintAction();
  if (!action) return; // user cancelled

  const html = await fetchPrintHtml(opts.path, opts.getToken);

  if (action === "print") {
    await Print.printAsync({ html });
    return;
  }

  // share PDF file
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  let shareUri = uri;
  try {
    const dir = FileSystem.cacheDirectory ?? "";
    const target = `${dir}${opts.fileName}`;
    await FileSystem.copyAsync({ from: uri, to: target });
    shareUri = target;
  } catch {
    // fall back to original URI on copy failure
  }

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(shareUri, {
      mimeType: "application/pdf",
      dialogTitle: opts.fileName,
      UTI: "com.adobe.pdf",
    });
  } else {
    throw new Error("この端末では共有機能が利用できません");
  }
}

async function fetchPrintHtml(
  path: string,
  getToken: () => Promise<string | null>,
): Promise<string> {
  const domain = process.env.EXPO_PUBLIC_DOMAIN;
  if (!domain) throw new Error("EXPO_PUBLIC_DOMAIN が未設定です");
  const token = await getToken();
  const url = `https://${domain}${path}`;
  const res = await fetch(url, {
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
  if (!res.ok) {
    throw new Error(`PDF 取得失敗 (HTTP ${res.status})`);
  }
  return await res.text();
}

type PrintAction = "print" | "share";

/** Show an OS-native action sheet to let the user choose what to do. */
function pickPrintAction(): Promise<PrintAction | null> {
  return new Promise((resolve) => {
    if (Platform.OS === "ios") {
      ActionSheetIOS.showActionSheetWithOptions(
        {
          title: "PDF・印刷",
          message: "操作を選択してください",
          options: ["キャンセル", "印刷する", "PDFを保存・共有"],
          cancelButtonIndex: 0,
        },
        (idx) => {
          if (idx === 1) resolve("print");
          else if (idx === 2) resolve("share");
          else resolve(null);
        },
      );
      return;
    }
    // Android / Web fallback: simple Alert with 3 buttons
    Alert.alert(
      "PDF・印刷",
      "操作を選択してください",
      [
        { text: "キャンセル", style: "cancel", onPress: () => resolve(null) },
        { text: "印刷する", onPress: () => resolve("print") },
        { text: "PDFを保存・共有", onPress: () => resolve("share") },
      ],
      { cancelable: true, onDismiss: () => resolve(null) },
    );
  });
}
